# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.4.1-fpm

pipelines:
  branches:
    master:
      - step:
          name: Perform Unit Testing Production
          services:
            - mysql
          script:
            - apt-get update && apt-get install -y libzip-dev zip default-mysql-client
            - docker-php-ext-install zip
            - docker-php-ext-install pdo_mysql
            - docker-php-ext-install zip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install --no-interaction --prefer-dist  --optimize-autoloader
            - ln -f -s .env.pipelines .env
            - php artisan migrate
            - vendor/bin/phpunit
      - step:
          name: Execute Production Deployment
          deployment: production
          trigger: manual
          script:
            - apt-get update && apt-get install -y libzip-dev zip
            - docker-php-ext-install zip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install --no-interaction --prefer-dist  --optimize-autoloader
            - composer require laravel/vapor-cli
            - ln -f -s .env.pipelines .env
            - vendor/bin/vapor deploy production
    staging:
      - step:
          name: Perform Unit Testing Staging
          services:
            - mysql
          script:
            - apt-get update && apt-get install -y libzip-dev zip default-mysql-client
            - docker-php-ext-install zip
            - docker-php-ext-install pdo_mysql
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install --no-interaction --prefer-dist  --optimize-autoloader
            - ln -f -s .env.pipelines .env
            - php artisan migrate
            - vendor/bin/phpunit
      - step:
          name : Execute Staging Deployment
          deployment: staging
          trigger: manual
          script:
            - apt-get update && apt-get install -y libzip-dev zip
            - docker-php-ext-install zip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install --no-interaction --prefer-dist  --optimize-autoloader
            - composer require laravel/vapor-cli
            - ln -f -s .env.pipelines .env
            - vendor/bin/vapor deploy staging
    develop:
      - step:
          name: Automated Test & Deploy to Develop
          services:
            - mysql
          deployment: test
          script:
            - apt-get update && apt-get install -y libzip-dev zip default-mysql-client
            - docker-php-ext-install zip
            - docker-php-ext-install pdo_mysql
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install --no-interaction --prefer-dist  --optimize-autoloader
            - composer require laravel/vapor-cli
            - ln -f -s .env.pipelines .env
            - php artisan migrate
            - vendor/bin/phpunit
            - vendor/bin/vapor deploy develop
definitions:
  services:
    mysql:
      image: mysql:8
      variables:
        MYSQL_DATABASE: 'pipelines'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'test_user'
        MYSQL_PASSWORD: 'test_user_password'

